var arr = ['stef', 25, true];
arr[0] = false;
arr[1] = 'ivan';
arr = [30, false, 'nick'];
var tup = ['jeff', 25, true];
tup[0] = 'ken';
tup[1] = 40;
var student;
student = ['George', 433];
//student = [433,'George'];
